server:
  port: 8080
  ssl:
    key-store: classpath:ssl/server.keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: server
spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/my_web?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false # ???????,??????????
    prefix: classpath:/templates/
    #    check-template: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
      mode:  HTML

